CREATE TABLE BANK12 (BANKCODE VARCHAR(3) PRIMARY KEY, BANKNAME VARCHAR(20) NOT NULL, HEADOFFICE VARCHAR(20), branches int check (branches > 0));

INSERT INTO BANK12 VALUES('STB','Bank of India','KOTTAYAM',7612);
INSERT INTO BANK12 VALUES('HDF', 'HDFC Bank', 'MUMBAI', 2500);
INSERT INTO BANK12 VALUES('ICR', 'ICICI Bank', 'BENGALURU', 1800);
INSERT INTO BANK12 VALUES('SBI', 'State Bank of India', 'NEW DELHI', 5000);
INSERT INTO BANK12 VALUES('AXI', 'Axis Bank', 'PUNE', 1200);
INSERT INTO BANK12 VALUES('MYB', 'My Bank', 'Ernakulam', 1200);


CREATE TABLE BRANCH(BRANCHID INT PRIMARY KEY,BRANCHNAME VARCHAR(20) DEFAULT 'New Delhi',BANKID VARCHAR(3),FOREIGN KEY(BANKID) REFERENCES BANK12(BANKCODE) ON DELETE CASCADE);

INSERT INTO BRANCH VALUES(100, 'kottayam','AXI');
INSERT INTO BRANCH VALUES(101, 'KADUTHURUTHY','STB');
INSERT INTO BRANCH VALUES(102, 'Pala','MYB');
INSERT INTO BRANCH VALUES(103, 'idukki','ICR');


SELECT * FROM BANK12;



delete from bank12 where bankcode = 'STB';

ALTER TABLE BRANCH DROP PRIMARY KEY;

CREATE VIEW BANK_HEAD_OFFICE AS SELECT * FROM BANK12 WHERE HEADOFFICE = 'Ernakulam';

select * from BANK_HEAD_OFFICE;

CREATE VIEW BANK_BRANCH AS SELECT bk.bankcode,bk.bankname,bk.headoffice,bk.branches FROM BANK12 BK JOIN BRANCH B ON BK.BANKCODE = B.BankID WHERE B.BRANCHNAME = 'kottayam';

select * from BANK_BRANCH;

drop view BANK_BRANCH;
