CREATE TABLE EMPLOYEE(EMP_ID NUMBER(3) PRIMARY KEY, EMP_NAME VARCHAR(20), DEPT VARCHAR(20), SALARY NUMBER(5));

INSERT INTO EMPLOYEE VALUES(1, 'ARON','HR',6000);
INSERT INTO EMPLOYEE VALUES(2, 'OLIVIA','Marketing',8000);
INSERT INTO EMPLOYEE VALUES(3, 'CHARLES BROWN','Sales',3000);
INSERT INTO EMPLOYEE VALUES(4, 'DAVID SMITH','Production',8000);
INSERT INTO EMPLOYEE VALUES(5, 'ABIN JACOB','HR',7500);


SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE SALARY > 7000;

UPDATE EMPLOYEE SET SALARY = 8200 WHERE EMP_NAME = 'DAVID SMITH';

INSERT INTO EMPLOYEE VALUES(6 ,'DANIEL HARRIS','Production',6700); 

DELETE FROM EMPLOYEE WHERE EMP_ID = 3;

SELECT * FROM EMPLOYEE WHERE EMP_NAME NOT LIKE 'D%' AND  EMP_NAME NOT LIKE 'O%';

SELECT DEPT,SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT; 

UPDATE EMPLOYEE SET SALARY = SALARY +(5/100)*SALARY WHERE DEPT = 'Production';

DELETE FROM EMPLOYEE WHERE SALARY < 7000;

SELECT EMP_NAME , SALARY FROM EMPLOYEE WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE);

UPDATE EMPLOYEE SET SALARY = 8200 WHERE DEPT = 'Marketing';

SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE 'A%';

SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE '%IT%';

SELECT DISTINCT UPPER(DEPT) FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE DEPT LIKE 'M_r%ket%';

SELECT DISTINCT UPPER(REVERSE(DEPT)) FROM EMPLOYEE;
