SELECT CEIL(8.29) FROM DUAL;
SELECT CEIL(-3.9) FROM DUAL;
SELECT CEIL(17/3) FROM DUAL;
SELECT FLOOR(9.76)FROM DUAL;
SELECT FLOOR(-5.3)FROM DUAL;
SELECT FLOOR(15/4)FROM DUAL;
SELECT SQRT(625)FROM DUAL;
SELECT SQRT(2) FROM DUAL;
SELECT ABS(8.29) FROM DUAL;
SELECT ABS(-3.14) FROM DUAL;
SELECT ABS(-42) FROM DUAL;
SELECT SYSDATE AS NOW FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY hh:mm:ss') AS FORMAT1, TO_CHAR(SYSDATE, 'dy') AS FORMAT2 FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT LEAST('APPLE','ORANGE','MANGO')FROM DUAL;
SELECT GREATEST('APPLE','ORANGE','MANGO') FROM DUAL;
SELECT LTRIM(' Trim me' ) FROM DUAL;
SELECT RTRIM('I love India                ' ) AS DATA FROM DUAL;
SELECT RPAD('Amal',15,'X')FROM DUAL;
SELECT RPAD(123,6,0) FROM DUAL;
SELECT REVERSE('uoy evol I')FROM DUAL;
SELECT CASE
 WHEN 'RACECAR'=REVERSE('RACECAR') THEN 'PALINDROME'
 ELSE 'NOT PALINDROME'
 END AS RESULT FROM DUAL ;
SELECT LENGTH('oracle database')FROM DUAL;
SELECT 'Oracle'||'SQL'||'is'||'powerful'||'flexible'  FROM DUAL;
SELECT CONCAT('Amal','Joy') FROM DUAL ;
SELECT SUBSTR('India is my country',7,2) FROM DUAL;
SELECT SUBSTR('Amal',1,3) FROM DUAL;
select SUBSTR('Substring',1,3) FROM DUAL;
